spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    baseUrl: http://localhost:9411/
eureka:
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
        
application:
  feeds:
    - 'JAVA'
    - 'SPRING'
    - 'MICROSERVICE'
    - 'CLOUD'



