spring:
  cloud:
    stream:
      function:
        definition: processMessage
      bindings:
        processMessage-in-0:         
          destination: messageInput
          consumer.headerMode: embeddedHeaders
        processMessage-out-0:
          destination: messageFeedback
          producer.headerMode: embeddedHeaders
        
